# Defaults
export EDITOR="nvim"
export PAGER="less"

# Keyboard
export XKB_DEFAULT_LAYOUT="ca"
export XKB_DEFAULT_OPTIONS="caps:escape"
export KEYTIMEOUT=10

# Sway
export XDG_RUNTIME_DIR="/run/user/1000"
export WLC_DRM_DEVICE="card1"
export _JAVA_AWT_WM_NONREPARENTING=1

# Go
export GOPATH="$HOME/.go"
export PATH="$PATH:$GOPATH/bin"
